import pyautogui
import webbrowser
import time


def sell(symbol):
    time.sleep(2)
    webbrowser.open("https://google.com", new=1)
    time.sleep(1.5)
    pyautogui.click(1032, 180, duration=0)
    pyautogui.hotkey('ctrl', 'command', 'f')
    time.sleep(1.5)
    pyautogui.moveTo(885, 0)
    pyautogui.moveTo(885, 20)
    pyautogui.click(885, 35, duration=0)
    time.sleep(1)
    pyautogui.typewrite("Robinhood")
    pyautogui.typewrite(["enter"])
    time.sleep(1)
    pyautogui.moveTo(300, 500)
    time.sleep(5)
    pyautogui.click(428, 34, duration=0)
    pyautogui.typewrite(symbol)
    time.sleep(2)
    pyautogui.typewrite(["enter"])
    time.sleep(2.5)
    pyautogui.click(1194, 125, duration=0)
    pyautogui.click(1290, 181, duration=0)
    pyautogui.typewrite("2")
    time.sleep(1)
    pyautogui.click(1267, 341, duration=0)
    time.sleep(1)
    pyautogui.click(1252, 451, duration=0)
    time.sleep(1)
    pyautogui.hotkey('command', 'w')


def buy(symbol):
    time.sleep(2)
    webbrowser.open("https://google.com", new=1)
    time.sleep(1.5)
    pyautogui.click(1032, 180, duration=0)
    pyautogui.hotkey('ctrl', 'command', 'f')
    time.sleep(1.5)
    pyautogui.moveTo(885, 0)
    pyautogui.moveTo(885, 20)
    pyautogui.click(885, 35, duration=0)
    time.sleep(1)
    pyautogui.typewrite("Robinhood")
    pyautogui.typewrite(["enter"])
    time.sleep(1)
    pyautogui.moveTo(300, 500)
    time.sleep(5)
    pyautogui.click(428, 34, duration=0)
    pyautogui.typewrite(symbol)
    time.sleep(2)
    pyautogui.typewrite(["enter"])
    time.sleep(2.5)
    pyautogui.click(1306, 185, duration=0)
    pyautogui.typewrite("1")
    pyautogui.click(1196, 351, duration=0)
    time.sleep(1)
    pyautogui.click(1262, 451, duration=0)
    time.sleep(1)
    pyautogui.hotkey('command', 'w')

sell("BIOS")

